### ISSUE TITLE
Feature req:  Usage of Vale software switch

### ISSUE THREAD

**Issue by mgamsjager** [churchers/vm-bhyve#73] opened 2016-03-15 12:14 UTC
Utilization of Vale software switch. Should be usable as of commit r296829

**Comment by churchers** [comment] 2016-03-15 15:46
Yes I saw information about this just the other day, although at the time there was a review open to fix some fundamental bugs.

I'm very interested in adding support for better networking features and will look into this in more detail when time is available.

**Comment by mgamsjager** [comment] 2016-03-15 17:34
Ok great. Can't wait :)

**Comment by churchers** [comment] 2016-04-08 20:58
I don't know if you have any better vale knowledge than me. I have experimental code in github (mainly just because I'm working on it in the same codebase I do my main development, so it's all been committed together), but the furthest I can get is panicking my machine.

So far I'm just passing the following option to bhyve -

    -s X:Y,virtio-net,vale12345:67890

This is based on info from the following gist 
https://gist.github.com/gonzopancho/f58516e98f6c8a5a3013
As far as I understand it (and confirmed on freebsd-net), this is a valid vale name (less than 16 chars), `12345` is the switch name, and `67890` is the port. `12345` is generated from an md5 of the switch name, so all guest interfaces on the same switch should get the same value, and `67890` is generated from an md5 of the guest interface mac, so different guests should get unique ports.

You're welcome to try it if you're brave, but as I say it just panics my machine. At the moment I have very little documentation to go on and this gist linked above is the literally the only mention I can find of using it with bhyve.

The only way to enable it at the moment is to create a switch by hand. Say your switch config (`/vm/path/.config/switch`) looks like the following:

    switch_list="public"
    ports_public="em0"

You can manually add a vale switch:

    switch_list="public valeswitch"
    vale_valeswitch="yes"

**Comment by mgamsjager** [comment] 2016-04-08 21:09
OK I have no vale experience but I will give it a go this weekend.

**Comment by mgamsjager** [comment] 2016-04-08 21:10
What build you are on?
Mine is: FreeBSD workstation 11.0-CURRENT FreeBSD 11.0-CURRENT #7 cc1aaf5(master)-dirty: Thu Apr  7 07:08:49 CEST 2016

**Comment by mgamsjager** [comment] 2016-04-08 21:16
Ok just git pulled
Edited the switch file
```
switch_list="publici valueswitch"
ports_public="em0"
vale_valeswitch="yes"
root@workstation:/zrt/vm/.config # vm switch info
------------------------
Virtual Switch: publici
------------------------
  type: auto
  ident: -
  vlan: -
  nat: -
  physical-ports: -

------------------------
Virtual Switch: valueswitch
------------------------
  type: auto
  ident: -
  vlan: -root@workstation:/zrt/vm/.config # vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
publici         auto       -           -         -            -
valueswitch     auto       -           -         -            -

  nat: -
  physical-ports: -


em0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=42098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWTSO>
	ether 00:1b:21:61:b0:01
	inet 192.168.2.141 netmask 0xffffff00 broadcast 192.168.2.255 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: vm-public
	ether 02:89:86:3a:e6:00
	nd6 options=1<PERFORMNUD>
	groups: bridge 
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
	member: tap0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 4 priority 128 path cost 2000000
	member: em0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 1 priority 128 path cost 20000
tap0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: vmnet-testvm-0-public
	options=80000<LINKSTATE>
	ether 00:bd:cf:c5:65:00
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	groups: tap 
	Opened by PID 76743

```

Not sure if vale is even running

**Comment by churchers** [comment] 2016-04-08 21:27
Double check the name in your switch config file - `valueswitch`.
The list and info output should look similar to the following

```
# vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          auto       bridge0     -         -            re0
valetest        vale       vale66aa9   n/a       n/a          n/a
#
# vm switch info valetest
------------------------
Virtual Switch: valetest
------------------------
  type: vale
  ident: vale66aa9
  vlan: -
  nat: -
  physical-ports: -
```

As far as i'm aware vale switches don't appear in `ifconfig` and everything should just be dynamic. I'm not had it working yet but I'm under the impression just requesting a vale port should create the netmap stuff on the fly.

**Comment by mgamsjager** [comment] 2016-04-08 21:34
Yeah typos
```
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          auto       bridge0     -         -            em0
valeswitch      vale       vale4fda5   n/a       n/a          n/a

root@workstation:/zrt/vm/testvm # vm switch info   
------------------------
Virtual Switch: public
------------------------
  type: auto
  ident: bridge0
  vlan: -
  nat: -
  physical-ports: em0
  bytes-in: 784564 (766.175K)
  bytes-out: 14687275 (14.006M)

------------------------
Virtual Switch: valeswitch
------------------------
  type: vale
  ident: vale4fda5
  vlan: -
  nat: -
  physical-ports: -
root@workstation:/zrt/vm/testvm # cat testvm.conf 
guest="freebsd"
cpu=1
memory=1G
network0_type="virtio-net"
network0_switch="valeswitch"
disk0_type="virtio-blk"
disk0_name="disk0.img"
uuid="2e090149-e0ae-11e5-b0b0-001b2161b001"
network0_mac="58:9c:fc:00:6e:fb"


```
Changed the network0_switch to vale but can't get a dhcp lease

**Comment by mgamsjager** [comment] 2016-04-08 21:46
Ok just for checking that vale is working;

installed /usr/src/tools/tools/netmap/pkt-gen
``` 
tcpdump -ni vale-a:1 &
pkt-gen  -i vale-a:0 -f tx &

This is from the man page of vale BUT it only works when using this


 tcpdump -ni vale0:1 &
pkt-gen  -i vale0:0 -f tx &


result:

Sent 577802752 packets, 60 bytes each, in 12.37 seconds.
Speed: 46.71 Mpps Bandwidth: 22.42 Gbps (raw 31.39 Gbps)

```

**Comment by churchers** [comment] 2016-04-08 21:47
Does the guest boot?
You won't get a dhcp lease if the guest is the only thing connected to the vale switch. If your guest actually does boot you should be able to start two guests on the same vale switch and communicate between them.

Apparently you should be able to use `vale-ctl` to attach a real interface to a vale switch. However not only does `vale-ctl` seem to be hidden away in `/usr/src/tools/tools/netmap/` but I can't find any documentation at all that makes any sense.

**Comment by mgamsjager** [comment] 2016-04-08 22:03
Ok both VM's can ping each other. 
```
root@workstation:/zrt/vm/testvm2 # vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          auto       bridge0     -         -            em0
valeswitch      vale       vale4fda5   n/a       n/a          n/a

root@workstation:/zrt/vm/testvm2 # vale-ctl 
bdg_ctl [149] bridge:0 port:0 vale4fda5:28bf7
bdg_ctl [149] bridge:0 port:1 vale4fda5:f1cb8
```

Missing part is now the bridge to the em0 interface.

**Comment by churchers** [comment] 2016-04-08 22:06
Cool
That's about as far as I can get with `vm-bhyve` at the moment seeing as the `vale-ctl` command only seems to exist under `/usr/src`. Getting this far is pretty impressive.

This *should* attach the host interface to it
```
vale-ctl -h vale4fda5:em0
```
If this command works and makes it into stable base I'll look at automating it

**Comment by mgamsjager** [comment] 2016-04-08 22:18
```
root@workstation:/zrt/vm/testvm2 # vale-ctl 
bdg_ctl [149] bridge:0 port:0 vale4fda5:28bf7
bdg_ctl [149] bridge:0 port:1 vale4fda5:f1cb8
bdg_ctl [149] bridge:0 port:2 vale4fda5:em0
bdg_ctl [149] bridge:0 port:3 vale4fda5:em0^
```
But that kills my normal traffic on em0. Guess a TAP device needs to be part of the vale switch and be bridged with em0
but that seems to be counter productive

**Comment by churchers** [comment] 2016-04-08 22:24
Hmm I don't actually know if that's expected or not. I was hoping "attach to the host stack" would mean that the host would still be able to communicate via em0.

Do the guests have full network access once em0 is part of the switch?

**Comment by mgamsjager** [comment] 2016-04-08 22:26
No they don't. Cant even ping vtnet0 -> em0 from inside the vm.
When em0 is part of the vale I can't even get an IP from the router dhcp

**Comment by churchers** [comment] 2016-04-08 22:31
Hmm I'll have to try and find some more information on how vale is supposed to communicate with physical networks. I've only seen examples of direct traffic between vale ports. Having guests communicate via vale is a decent step forward though.

**Comment by gonzopancho** [comment] 2016-04-13 05:00
Let me know if you want some help here.   (I wrote the gist you quote above.)

**Comment by mgamsjager** [comment] 2016-04-13 05:52
@gonzopancho Well I for one would like to know how to make normal interface (em0) part of a valeswitch so that each VM has access to the network. 

Pinging VM0 -> vale -> VM1 works fine but other then that no much is happening

**Comment by churchers** [comment] 2016-04-13 06:59
Thanks for the offer @gonzopancho Any insights would be greatly appreciated.

Guest to guest communication seems to be fine (purely based on reports from @mgamsjager), I just can't find much information (or examples) on connecting to a real network. It doesn't help that I can't really test anything myself - I have one machine I can do bhyve work on, and it panics as soon as I create a vale interface.

As above, I just pass valeX:Y to bhyve, based on your gist, with X being based on an MD5 of the switch name (so we can handle multiple switches), and Y based on an MD5 of the guest mac. When I originally started getting panics I asked on the mailing list, just in case I was providing invalid port names, and one of the main netmap devs confirmed that up to 5 characters for switch & port name should be acceptable.

It would be nice just to know if it's actually possible to get vale to the point where guests can communicate between themselves, the network and the host (similar to the functionality we currently get with bridging). The fact that the `vale-ctl` commands lists a 'connect to the host stack' option does seem to suggest to me that it should be possible.

If vale can communicate via a real interface, but not with the host that would be fine as long as I know and can document it - users will just need to add an additional `bridge` based switch if the guests and host need to communicate directly. Even if vale takes over the entire interface, meaning only vale ports can use it, I can just mention that vale needs a dedicated interface. 

I just don't know at the moment, have no way of testing, and haven't found any example anywhere of someone actually connecting a bhyve guest to a physical network with vale. (Yours is about the only real example I have found)

**Comment by churchers** [comment] 2016-05-17 11:50
Vale is still on the todo list.
Closing this for now until I have the ability to do actual testing. It all seems a bit experimental at the moment, although the outcome of this Soc2016 project may be interesting.
https://wiki.freebsd.org/SummerOfCode2016/PtnetDriverAndDeviceModel

**Closed by churchers** 2016-05-17 11:50 UTC
Labels: enhancement

**Comment by gonzopancho** [comment] 2016-06-16 10:04
I'll take a look at it.  We're working on netmap-fwd again.

**Comment by janvs0** [comment] 2021-02-11 16:28
Is this still on the radar? (It seems https://github.com/churchers/vm-bhyve/blob/master/lib/vm-switch-vale is stale).

I did manage to get this running using a type vale switch on 12.2-RELEASE and manually adding the physical interface (with promiscuous mode enabled) to it. This now provides the same functionality as bridging.
